# Generated by Django 5.2.10 on 2026-01-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='community',
            field=models.CharField(blank=True, choices=[('BC', 'BC'), ('MBC', 'MBC'), ('SC', 'SC'), ('ST', 'ST'), ('OC', 'OC'), ('OBC', 'OBC')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_first_graduate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='core.staffprofile'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='residence',
            field=models.CharField(blank=True, choices=[('Day Scholar', 'Day Scholar'), ('Hosteller', 'Hosteller')], max_length=20, null=True),
        ),
    ]
