# Generated by Django 5.2.10 on 2026-01-12 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staffprofile_address_staffprofile_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='ahod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahod_department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='core.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('ACADEMIC', 'Academic'), ('NON_ACADEMIC', 'Non Academic'), ('FIRST_YEAR', 'First Year')], default='ACADEMIC', max_length=20),
        ),
    ]
