# Generated by Django 5.2.10 on 2026-01-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_ahod_department_parent_department_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='C',
            field=models.FloatField(default=0, help_text='Total credits'),
        ),
        migrations.AddField(
            model_name='course',
            name='L',
            field=models.FloatField(default=0, help_text='Lecture credits'),
        ),
        migrations.AddField(
            model_name='course',
            name='P',
            field=models.FloatField(default=0, help_text='Practical credits'),
        ),
        migrations.AddField(
            model_name='course',
            name='S',
            field=models.FloatField(default=0, help_text='Self-study credits'),
        ),
        migrations.AddField(
            model_name='course',
            name='T',
            field=models.FloatField(default=0, help_text='Tutorial credits'),
        ),
        migrations.AddField(
            model_name='course',
            name='admin_department_name',
            field=models.CharField(default='General', help_text='Manually entered department name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='Others', help_text='Course category (e.g., PC, ES, PE, HS)', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='class_types',
            field=models.JSONField(default=list, help_text="List of class types: ['Theory', 'Practical']"),
        ),
        migrations.AddField(
            model_name='course',
            name='external_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='internal_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1, help_text='Semester (1-8)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='target_departments',
            field=models.ManyToManyField(blank=True, help_text='Departments that study this course', related_name='curriculum_courses', to='core.department'),
        ),
    ]
