# Generated by Django 5.2.10 on 2026-01-13 08:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_course_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_year', models.PositiveIntegerField(help_text='Joining year, e.g. 2023')),
                ('semester', models.PositiveSmallIntegerField(help_text='Semester (1-8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('courses', models.ManyToManyField(blank=True, help_text='Courses allocated for this department/batch/semester', related_name='allocations', to='core.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to='core.department')),
            ],
            options={
                'verbose_name': 'Course Allocation',
                'verbose_name_plural': 'Course Allocations',
                'unique_together': {('department', 'batch_year', 'semester')},
            },
        ),
    ]
