# Generated by Django 5.2.10 on 2026-01-13 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_courseallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_year', models.PositiveIntegerField(help_text='Joining year, e.g., 2024')),
                ('section', models.CharField(help_text='Section code, e.g., A, B, C', max_length=10)),
                ('department', models.ForeignKey(help_text='Department for the class', on_delete=django.db.models.deletion.CASCADE, related_name='class_advisors', to='core.department')),
                ('staff', models.ForeignKey(help_text='Staff member acting as class advisor', on_delete=django.db.models.deletion.CASCADE, related_name='advised_classes', to='core.staffprofile')),
            ],
            options={
                'verbose_name': 'Class Advisor',
                'verbose_name_plural': 'Class Advisors',
                'unique_together': {('department', 'batch_year', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_year', models.PositiveIntegerField(help_text='Joining year, e.g., 2024')),
                ('section', models.CharField(help_text='Section code, e.g., A, B, C', max_length=10)),
                ('semester', models.PositiveSmallIntegerField(help_text='Semester (1-8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], help_text='Day of the week', max_length=10)),
                ('period', models.PositiveSmallIntegerField(help_text='Period number (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('department', models.ForeignKey(help_text='Department for the class', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.department')),
                ('subject', models.ForeignKey(blank=True, help_text='Course/subject for this slot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='core.course')),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
                'unique_together': {('department', 'batch_year', 'section', 'semester', 'day', 'period')},
            },
        ),
    ]
