# Generated by Django 5.2.10 on 2026-01-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_classadvisor_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Curriculum Batch',
                'verbose_name_plural': 'Curriculum Batches',
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='batch_year',
            field=models.IntegerField(blank=True, help_text='Year the student joined, used for curriculum mapping', null=True),
        ),
    ]
