# Generated by Django 5.2.10 on 2026-01-13 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_curriculumbatch_studentprofile_batch_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who proposed or created this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether the course proposal is approved'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Whether the course proposal was rejected'),
        ),
    ]
