# Generated by Django 5.2.10 on 2026-01-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course_created_by_course_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether the course proposal is approved'),
        ),
    ]
